### ISSUE TITLE
Neotech Windows Server Donwload Fails Files

### ISSUE THREAD

**Issue by ghost** [CreeperHost/modpacksch-serverdownloader#19]
I am trying to download the server installer for NeoTech 1.1.0 (and all previous versions) and every time i do the install for the server installer the download always failed with x number of downloads failed. If you continue pass by accepting the errors the server will start and run, I just do not know if these failed downloads will affect gameplay (assuming it could) and if i were to manually download them, where to place them. This is for windows.

https://pastebin.com/DZ1Qfifk (errors only)
https://paste.feed-the-beast.com/view/445546f1 (Full log)

Steps to reproduce
1. Download the server installer from https://www.feed-the-beast.com/modpacks/server-files 2. place in a folder 3. double click to run 4. press enter to install to current directory 5. press y to still install 6. press y to continue with 1.1.0 version 7. read how many downloads failed and choose y to continue or n to not.

**Comment by ThePaul-T** [comment]
Can you confirm this is still ongoing and these are not old logs? There was a maven that provides required libraries that was behind Cloudflare with their browser protection still enabled, so the server installer would hit that and be unable to grab the libraries.

This was reported and resolved, so I am trying to grasp if the issue is still ongoing or if it fully resolved it.

**Comment by ghost** [comment]
Can confirm this is still an issue. https://paste.feed-the-beast.com/view/003f5337 this is a log from 6/21 11pm cst.

**Comment by ThePaul-T** [comment]
Please try again now and let us know if the issue is not resolved.

**Comment by ghost** [comment]
Works now!
