### ISSUE TITLE
Installer applies urlencoding for addresses with url encoded file part

### ISSUE THREAD

**Issue by jikuja** [CreeperHost/modpacksch-serverdownloader#5]
**Installer version:**
 modpacks.ch server downloader golang - build 21.429.1632-darwin-amd64
 based on commit c44f43c23b31061706f9eba77b016e963055233a

**The problem:**
Running e.g. `serverinstall_20_102 20 102 --auto` (FTB Infinity Evolved Skyblock) fails to download two mods:

> Error downloading https://dist.modpacks.ch/jds/bibliowood/naturawood/1.5/BiblioWoods%255BNatura%255D%255Bv1.5%255D.jar: checksum mismatch
> Error downloading https://dist.modpacks.ch/jds/bibliowood/forestrywood/1.7/BiblioWoods%255BForestry%255D%255Bv1.7%255D.jar: checksum mismatch

and we can clearly see that the filename is run through the URL encode process twice. 

https://api.modpacks.ch/public/modpack/20/102 returns addresses with URL encoding and installer probably does encoding again and is the requesting **BiblioWoods%5BNatura%5D%5Bv1.5%5D.jar** instead of **BiblioWoods[Natura][v1.5].jar**

Because of this bug server downloaded misses all files containing at least character [ and ] and other defined as reserved on RFC 3986.

**Comment by ThePaul-T** [comment]
Looks like it is downloading fine, error states checksum mismatch. Url is double encoded due to the developer of the mod upload API messing up early on and encoding URLs twice (Basically, they actually encoded the file when storing on the filesystem too, then encoded the URL when storing it to the database of mods...)

Download completed, but checksum delivered server side is incorrect, so either file is corrupted or checksum was stored wrong at upload time.

Thanks for reporting, if you find any more files with a checksum mismatch, please report them to FTB so they can be investigated and files replaced in the packs.
